= Octoprint slicing profiles for CURA on Rostock MAX
:toc:

== License

The materials for this class are licensed under the Apache license. See the file LICENSE for details.

Copyright 2016 F Douthit

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

== Description
These are the basic sliding profiles we've created for our Rostock MAX (not V2). Use at your own risk.

== New Profiles 2016-07

These new profiles were created by comparing the output of Matter Control with the output of Cura and tweaking the Cura profiles to more closely emulate the Matter Control settings.

`PLA_high-quality_Rostock_cura.ini`:: 0.1 mm layer height

`PLA_high-speed_Rostock_cura.ini`:: 0.2 mm layer height

`PLA_medium-quality_Rostock_cura.ini`:: 0.3 mm layer height, with 105% flow rate

